### ISSUE TITLE
Problems with bento "customization" example

### ISSUE THREAD

**Issue by SirVer** [cournape/Bento#34] opened 2010-09-14 20:17 UTC
I am currently evaluating bento for building my tree of loosely coupled scientific research python modules. The all reside in one directory and there are some cython and swig sub modules mixed in. Currently I am using fbuild, but bento looks much more on the spot for my problem. 

I ran into a bug trying out the 
Bento/examples/hooks/customization 
example which seems to do something along the lines that I need.
bentomaker configure crashes with:
bentomaker: Error: bentomaker crashed (uncaught exception <type 'exceptions.ImportError'>: No module named conftests).

python version is 2.6, OS is Mac OS X 10.6.
Bento version is 5efb0e8c70 (BUG: fix _compute_extension_name when local_node is the top node.).

full output of
$ BENTOMAKER_DEBUG=1 bentomaker configure:

```
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 337, in noexc_main
 ret = main(argv)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 135, in main
 _wrapped_main(popts)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 143, in _wrapped_main
 return _main(popts)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 198, in _main
 run_cmd(cmd_name, cmd_opts)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 322, in run_cmd
 set_local_ctx(ctx, cmd_func, local_dir)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bentomakerlib/bentomaker.py", line 314, in set_local_ctx
 return hook(ctx)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bento/commands/configure.py", line 186, in run
 yaku_ctx.use_tools(["pyext"])
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bento/private/_yaku/yaku/context.py", line 47, in use_tools
 _t = self.load_tool(t, tooldir)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bento/private/_yaku/yaku/context.py", line 31, in load_tool
 _t = import_tools([tool], tooldir)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bento/private/_yaku/yaku/tools/__init__.py", line 17, in import_tools
 ret[t] = __import__(t)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bento/private/_yaku/yaku/tools/pyext.py", line 28, in <module>
 from yaku.conftests \
bentomaker: Error: bentomaker crashed (uncaught exception <type 'exceptions.ImportError'>: No module named conftests).
Please report this on bento issue tracker:
 http://github.com/cournape/bento/issues
```

**Comment by cournape** [comment] 2010-09-15 05:43
Thanks for the bug report. Just to be clear, bento is still very much in development phase (and master not stable), so if you need any kind of stability, do not use it (at least not an unreleased version).

That being said, your error is caused by yaku not being up to date with bento. So you need to get a recent version of bento, and then tell bento not to use the bundled yaku version but the updated one. IOW:

```
export BENTO_UNBUNDLE_YAKU=1
export PYTHONPATH=YAKU_LOCATION:$PYTHONPATH
```

Then it should work.

**Comment by SirVer** [comment] 2010-09-15 09:16
I will try that. But wouldn't it be wise to bundle yaku as a git submodule or git subtree into Bento? This would stop the bundled yaku to go out of sync with bento and would avoid having the code floating around twice.

**Comment by cournape** [comment] 2010-09-15 09:30
I don't like submodule - they are too complicated to use (which is why it is bundled). I keep yaku out of bento because I am still not sure yaku is warranted at all, and also to force myself to have very clear boundaries.

Note that every release of bento does include the synced yaku.

**Comment by cournape** [comment] 2010-09-17 02:46
It should work now -  I have merged yaku changes into bento

**Closed as completed by cournape** 2010-09-17 02:46 UTC
